export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  VERIFY_EMAIL: '/verify-email',
  PROBLEMS: '/problems',
  PROBLEM_DETAIL: (slug: string) => `/problems/${slug}`,
  SUBMISSIONS: '/submissions',
  LEADERBOARD: '/leaderboard',
  PROFILE: '/profile',
  ACHIEVEMENTS: '/achievements',
  USER_PROFILE: (username: string) => `/users/${username}`,
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  NOT_FOUND: '/404',
} as const
